import { Cell } from "@/types";

const grid: Cell[][] = [
  Array(15).fill({ blocked: true }),
  [
    { blocked: true },
    { answer: "B", direction: "down", isFirstLetter: true },
    { blocked: true },
    { blocked: true },
    { answer: "S", direction: "down", isFirstLetter: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
  ],
  [
    { blocked: true },
    { answer: "U", direction: "down" },
    { blocked: true },
    { blocked: true },
    { answer: "A", direction: "down" },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { answer: "C", direction: "down", isFirstLetter: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
  ],
  [
    { blocked: true },
    { answer: "D", direction: "down" },
    { blocked: true },
    { answer: "A", direction: "across", isFirstLetter: true },
    { answer: "S", direction: "across" },
    { answer: "S", direction: "across" },
    { answer: "E", direction: "across" },
    { answer: "T", direction: "across" },
    { answer: "S", direction: "across" },
    { blocked: true },
    { answer: "I", direction: "down", isFirstLetter: true },
    { answer: "R", direction: "down" },
    { blocked: true },
    { blocked: true },
    { blocked: true },
  ],
  [
    { blocked: true },
    { answer: "G", direction: "down" },
    { blocked: true },
    { blocked: true },
    { answer: "V", direction: "down" },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { answer: "R", direction: "down" },
    { answer: "E", direction: "down" },
    { blocked: true },
    { blocked: true },
    { blocked: true },
  ],
  [
    { blocked: true },
    { answer: "E", direction: "down", isFirstLetter: true },
    { answer: "Q", direction: "across" },
    { answer: "U", direction: "across" },
    { answer: "I", direction: "across" },
    { answer: "T", direction: "across" },
    { answer: "Y", direction: "across" },
    { blocked: true },
    { answer: "B", direction: "across", isFirstLetter: true },
    { answer: "O", direction: "across" },
    { answer: "N", direction: "across" },
    { answer: "D", direction: "across" },
    { blocked: true },
    { blocked: true },
    { blocked: true },
  ],
  [
    { blocked: true },
    { answer: "T", direction: "down" },
    { blocked: true },
    { blocked: true },
    { answer: "N", direction: "down" },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { answer: "A", direction: "down" },
    { answer: "I", direction: "down" },
    { answer: "T", direction: "down", isFirstLetter: true },
    { blocked: true },
    { blocked: true },
  ],
  [
    { blocked: true },
    { answer: "I", direction: "down" },
    { blocked: true },
    { answer: "D", direction: "across", isFirstLetter: true },
    { answer: "I", direction: "across" },
    { answer: "V", direction: "across" },
    { answer: "I", direction: "across" },
    { answer: "D", direction: "across" },
    { answer: "E", direction: "across" },
    { answer: "N", direction: "across" },
    { answer: "D", direction: "across" },
    { answer: "S", direction: "across" },
    { answer: "A", direction: "down" },
    { blocked: true },
    { blocked: true },
  ],
  [
    { blocked: true },
    { answer: "N", direction: "down" },
    { blocked: true },
    { blocked: true },
    { answer: "G", direction: "down" },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { answer: "E", direction: "down" },
    { answer: "T", direction: "down" },
    { answer: "X", direction: "down" },
    { blocked: true },
    { blocked: true },
  ],
  [
    { blocked: true },
    { answer: "G", direction: "down" },
    { blocked: true },
    { answer: "Y", direction: "across", isFirstLetter: true },
    { answer: "I", direction: "across" },
    { answer: "E", direction: "across" },
    { answer: "L", direction: "across" },
    { answer: "D", direction: "across" },
    { blocked: true },
    { blocked: true },
    { answer: "B", direction: "down" },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
  ],
  [
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { answer: "S", direction: "down" },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { answer: "T", direction: "down" },
    { answer: "R", direction: "down", isFirstLetter: true },
    { answer: "O", direction: "down" },
    { blocked: true },
    { blocked: true },
  ],
  [
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { answer: "K", direction: "down" },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { answer: "I", direction: "down" },
    { answer: "I", direction: "down" },
    { blocked: true },
    { blocked: true },
  ],
  [
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { blocked: true },
    { answer: "S", direction: "down" },
    { blocked: true },
    { blocked: true },
    { blocked: true },
  ],
  Array(15).fill({ blocked: true }),
];

export default grid;
